const getters = {
    getMerchantInfo(state){
        return state.merchantInfo
    },
    bankSub(state){
        return {
            bankCode:state.merchantInfo.accountBankCode,
            bankCityId:state.merchantInfo.accountAddressCityCode
        }
    },
    applyStep(state){
        return {
            2:[
                //开户人姓名
                'accountName',
                //身份证号
                'idCard',
                //开户银行
                'accountBank',
                //银行卡号
                'accountNumber',
                //开户省市
                'accountAddressProvince',
                'accountAddressCity',
                //开户支行
                'accountSubBank',
                //手机号码
                'userTelNumber',
                //验证码
                'authCode',
                //营业执照
                'businessLicensePic',
            ],
            1:[
                'accountName',
                //开户银行
                'accountBank',
                //银行卡号
                'accountNumber',
                //开户省市
                'accountAddressProvince',
                'accountAddressCity',
                //开户支行
                'accountSubBank',
                //手机号码
                'userTelNumber',
                //验证码
                'authCode',
                //营业执照
                'businessLicensePic',
            ]
        }
    },
    clearList(){
        return[
            //开户人姓名
            'accountName',
            //身份证号
            'idCard',
            //开户银行
            'accountBank',
            'accountBankCode',
            //银行卡号
            'accountNumber',
            //开户省市
            'accountAddressProvince',
            'accountAddressProCode',
            'accountAddressCity',
            'accountAddressCityCode',
            //开户支行
            'accountSubBank',
            'accountSubBankCode',
            //手机号码
            'userTelNumber',
            //验证码
            'authCode',
            //营业执照
            'businessLicensePic',
        ]
    },
    getAccountSubBank(state){
        return state.merchantInfo.accountSubBank
    }
}
export default getters

